# Generated by Django 4.2.7 on 2023-11-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='review_qty',
            new_name='reviews_qty',
        ),
    ]
